### ISSUE TITLE
Multiedit select all problem when cursor at end of word

### ISSUE THREAD

**Issue by davidhealey** [rgieseke/ta-common#2]
Placing the cursor at the end of a word, then holding shift and pressing the left arrow to highlight the word results in an error when using the select_all command.

`multiedit.lua:61: attempt to index a nil value (field '?')`

**Comment by rgieseke** [comment]
Thanks for the report! I haven't actually used this functionality in quite a while ...

**Comment by rgieseke** [comment]
I've setup this in my iniy.lua:

```lua
local common = require("common")
keys['ctrl+alt+D'] = common.multiedit.select_all
```

This works as expected for selecting all words if nothing is selected, i'm not sure i understand the condition you describe above.

E.g. move over "common", press Ctrl-Alt-Shift-D selects all occurrences of "common", if something is already selected it doesn't work.

**Comment by davidhealey** [comment]
Highlight a word so that the caret is at the end of the word once it is highlight. What I did was place the caret at the start of the word and held shift and pressed the right arrow to highlight the word. Then use the select_all command.

**Comment by rgieseke** [comment]
Hm, i place the cursor on "c" in "common, press Ctrl-Shift-Arrow-Right, "common" is selected, I press "Ctrl-Alt+Shift+D", all 3 are selected.

**Comment by rgieseke** [comment]
Ah, got it, if i do it manually, one char further to the right, i can reproduce.

**Comment by rgieseke** [comment]
I'm wondering if i should retire the `multiedit` sub-module.

For select all one can use

```lua
keys['ctrl+alt+D'] = function() textadept.editing.select_word(true) end
```

There is also https://orbitalquark.github.io/textadept/api.html#textadept.history now, so maybe that's an easier way to restore positions if needed for multiple selections.

**Comment by davidhealey** [comment]
Yeah I think you're right, I hadn't noticed that command before.

**Comment by rgieseke** [comment]
Me neither :-)
Thanks for report, i've removed it in https://github.com/rgieseke/ta-common/commit/21499f039a015f02c5337e8e5ca7b3f0900a9a24
